# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0003_remove_projects_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-id']},
        ),
    ]
