# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0004_auto_20191020_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
